name: 京东多合一

on:
    workflow_dispatch:
    watch:
        types: [started]
    repository_dispatch:
        types: jd_all_in_one

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        env:
            #推送专用
            PUSH_KEY: ${{ github.event.client_payload.PUSH_KEY || secrets.PUSH_KEY }} # 微信推送 http://sc.ftqq.com/3.version
            BARK_PUSH: ${{ github.event.client_payload.BARK_PUSH || secrets.BARK_PUSH }} # BARK推送
            BARK_SOUND: ${{ github.event.client_payload.BARK_SOUND || secrets.BARK_SOUND }} # bark推送声音设置，例如choo,具体值请在bark-推送铃声-查看所有铃声
            TG_BOT_TOKEN: ${{ github.event.client_payload.TG_BOT_TOKEN || secrets.TG_BOT_TOKEN }} # tg推送,填写自己申请@BotFather的Token,如10xxx4:AAFcqxxxxgER5uw
            TG_USER_ID: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }} # tg推送,填写@getuseridbot中获取到的纯数字ID
            TG_PROXY_HOST: ${{ github.event.client_payload.TG_USER_ID || secrets.TG_USER_ID }} # Telegram 代理的IP,例子：http代理 http://127.0.0.1:1080 则填写 127.0.0.1
            TG_PROXY_PORT: ${{ github.event.client_payload.TG_PROXY_PORT || secrets.TG_PROXY_PORT }} # Telegram 代理的Port,例子：http代理 http://127.0.0.1:1080 则填写 1080
            DD_BOT_TOKEN: ${{ github.event.client_payload.DD_BOT_TOKEN || secrets.DD_BOT_TOKEN }} # 钉钉推送官方文档 ,只需https://oapi.dingtalk.com/robot/send?access_token=XXX 等于符号后面的XXX， 注：如果钉钉推送只填写DD_BOT_TOKEN，那么安全设置需勾选自定义关键词，内容输入输入账号即可，其他安全设置不要勾选
            DD_BOT_SECRET: ${{ github.event.client_payload.DD_BOT_SECRET || secrets.DD_BOT_SECRET }} # 密钥，机器人安全设置页面，加签一栏下面显示的SEC开头的字符串 , 注:填写了DD_BOT_TOKEN和DD_BOT_SECRET，钉钉机器人安全设置只需勾选加签即可，其他选项不要勾选
            IGOT_PUSH_KEY: ${{ github.event.client_payload.IGOT_PUSH_KEY || secrets.IGOT_PUSH_KEY }} # iGot聚合推送，支持多方式推送，确保消息可达. 参考 https://wahao.github.io/Bark-MP-helper
            QQ_SKEY: ${{ github.event.client_payload.QQ_SKEY || secrets.QQ_SKEY }} # QQ酷推, 酷推skey ,https://cp.xuthus.cc/docs
            QQ_MODE: ${{ github.event.client_payload.QQ_MODE || secrets.QQ_MODE }} # QQ酷推模式,酷推推送方式默认为私聊send推送，可以填写group改变为群聊推送
            PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }} # pushplus推送，微信扫码登录后一对一推送或一对多推送下面的token(您的Token)，不提供PUSH_PLUS_USER则默认为一对一推送 https://pushplus.hxtrip.com/
            PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }} # 一对多推送的“群组编码”（一对多推送下面->您的群组(如无则新建)->群组编码，如果您是创建群组人。也需点击“查看二维码”扫描绑定，否则不能接受群组消息推送）
            #通用配置
            JD_COOKIE: ${{ github.event.client_payload.JD_COOKIE || secrets.JD_COOKIE }} # 京东cookie,多个账号的cookie使用&隔开或者换行。具体获取参考https://github.com/lxk0301/jd_scripts/wiki/GetCookies
            JD_DEBUG: ${{ github.event.client_payload.JD_DEBUG || secrets.JD_DEBUG }} # 运行脚本时，是否显示log,默认显示。改成false表示不显示，注重隐私的人可以在设置secret -> Name:JD_DEBUG,Value:false
            DO_NOT_FORK: ${{ github.event.client_payload.DO_NOT_FORK || secrets.DO_NOT_FORK }} #没啥用了
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: 使用 Node.js 环境
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install

            - name: "运行 【京东进店领豆】4s/账号"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_shop.js

            - name: "运行【京东十元街】(2s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_syj.js

            - name: "运行 【京豆昨日收益】(5s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_bean_change.js

            - name: "运行 【京东快递】(3s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_kd.js

            - name: "运行 【京东金融天天提额】(5s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_daily_egg.js

            - name: "运行 【京东汽车】(10s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_car.js

            - name: "运行 【京东排行榜】(15s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/yangtingxiao/QuantumultX/raw/master/scripts/jd/jd_rankingList.js

            - name: "运行【京喜每日签到】(25s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/Sunert/Scripts/raw/master/Task/jingxi.js

            - name: "运行【抽京豆】(30s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_club_lottery.js

            - name: "运行 【京东每日签到】(30s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_bean_sign.js
                  JD_BEAN_STOP: ${{ github.event.client_payload.JD_BEAN_STOP || secrets.JD_BEAN_STOP }} # 自定义延迟签到,单位毫秒. 默认分批并发无延迟. 延迟作用于每个签到接口, 如填入延迟则切换顺序签到(耗时较长),如需填写建议输入数字1
                  JD_BEAN_SIGN_STOP_NOTIFY: ${{ secrets.JD_BEAN_SIGN_STOP_NOTIFY || github.event.client_payload.JD_BEAN_SIGN_STOP_NOTIFY}} # jd_bean_sign.js脚本运行后不推送签到结果通知，默认推送，填true表示不发送通知
                  JD_BEAN_SIGN_NOTIFY_SIMPLE: ${{ secrets.JD_BEAN_SIGN_NOTIFY_SIMPLE || github.event.client_payload.JD_BEAN_SIGN_NOTIFY_SIMPLE}} # jd_bean_sign.js脚本运行后推送签到结果简洁版通知，默认推送全部签到结果，填true表示推送简洁通知

            - name: "运行【京东领京豆额外奖励】(25s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_bean_home.js

            - name: "运行 【京喜签到】40s/账号"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jx_sign.js

            - name: "运行 【京东现金】25s/账号"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_cash.js

            - name: "运行 【京东赚赚】30s/账号"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_jdzz.js
                  JDZZ_SHARECODES: ${{ github.event.client_payload.JDZZ_SHARECODES || secrets.JDZZ_SHARECODES }} # 京东赚赚(jd_jdzz.js)脚本互助码

            - name: "运行 【京东金融养猪猪】(35s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_pigPet.js

            - name: "运行【泡泡大战】(45s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/799953468/Quantumult-X/raw/master/Scripts/JD/jd_paopao.js

            - name: "运行 【京东盲盒】50s/账号 - 02.05结束"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://raw.githubusercontent.com/shylocks/Loon/main/jd_mh.js

            - name: "运行 【年货节】60s/账号 - 02.09结束"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_nh.js

            - name: "运行 【东东小窝】(60s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_small_home.js

            - name: "运行【京小超领蓝币(小费)】(90s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_blueCoin.js
                  MARKET_COIN_TO_BEANS: ${{ github.event.client_payload.MARKET_COIN_TO_BEANS || secrets.MARKET_COIN_TO_BEANS }} # 京小超兑换京豆数量，可输入值为20或者1000的数字或者其他商品的名称,例如碧浪洗衣凝珠
                  MARKET_REWARD_NOTIFY: ${{ github.event.client_payload.MARKET_REWARD_NOTIFY || secrets.MARKET_REWARD_NOTIFY }} # 京小超兑换奖品推送开关，false为否(发送推送通知消息),true为是(即：不发送推送通知消息)
                  SUPERMARKET_UPGRADE: ${{ github.event.client_payload.SUPERMARKET_UPGRADE || secrets.SUPERMARKET_UPGRADE }} # 京小超自动升级，自动升级,顺序:解锁升级商品、升级货架,true表示自动升级,false表示关闭自动升级
                  BUSINESS_CIRCLE_JUMP: ${{ github.event.client_payload.BUSINESS_CIRCLE_JUMP || secrets.BUSINESS_CIRCLE_JUMP }} # 京小超自动更换商圈，小于对方300热力值自动更换商圈队伍,true表示运行,false表示禁止
                  SUPERMARKET_LOTTERY: ${{ github.event.client_payload.SUPERMARKET_LOTTERY || secrets.SUPERMARKET_LOTTERY }} # 京小超抽奖，每天运行脚本是否使用金币去抽奖,true表示抽奖,false表示不抽奖

            - name: "运行 【苹果抽奖机】- 1214"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_apple_live.js

            - name: "运行 【东东抽奖机+新店福利+东东福利屋+东东生活+闪购盲盒+疯狂砸金蛋】(9min/账号)"
              timeout-minutes: 60
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/yangtingxiao/QuantumultX/raw/master/scripts/jd/jd_lotteryMachine.js

            - name: "运行 【京东取关店铺】(30s/账号)"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://github.com/lxk0301/jd_scripts/raw/master/jd_unsubscribe.js
                  UN_SUBSCRIBES: ${{ github.event.client_payload.UN_SUBSCRIBES || secrets.UN_SUBSCRIBES }} # 共四个参数,换行隔开. 四个参数分别表示取关商品数量,取关店铺数量,遇到此商品不再进行取关, 遇到此店铺不再进行取关

            - name: "运行 【京东CrazyJoy日常任务】2min/账号"
              timeout-minutes: 30
              run: |
                  node execute.js
              env:
                  SYNCURL: https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_crazy_joy.js
                  JDJOY_HELPSELF: ${{ github.event.client_payload.JDJOY_HELPSELF || secrets.JDJOY_HELPSELF }} # 疯狂的joy循环助力，`true`表示循环助力,`false`表示不循环助力，默认不开启循环助力。
                  JDJOY_APPLYJDBEAN: ${{ github.event.client_payload.JDJOY_APPLYJDBEAN || secrets.JDJOY_APPLYJDBEAN }} # 疯狂的joy京豆兑换，目前最小值为500/1000京豆，默认不开启京豆兑换。
