# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Webhook通用触发

on:
    workflow_dispatch:
    schedule:
        - cron: "0 2,9,19 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_temp

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: 设置运行环境-Node.js 10.x
              uses: actions/setup-node@v1
              with:
                  node-version: 10.x
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行 【Webhook】"
              timeout-minutes: 350
              run: |
                  node execute.js
              env:
                  #推送专用
                  ENVS_FROM_WEBHOOK: ${{ github.event.client_payload.ENVS_FROM_WEBHOOK }}